"""add lessons to course v.5

Revision ID: 06d403e09fdb
Revises: e620fab49bdb
Create Date: 2026-02-15 17:38:11.002371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06d403e09fdb'
down_revision: Union[str, Sequence[str], None] = 'e620fab49bdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

course_table = sa.Table(
    "courses",
    sa.MetaData(),
    sa.Column("id", sa.Integer),
    sa.Column("name", sa.String),
    sa.Column("course_code", sa.String),
    sa.Column("course_semester", sa.String),
    sa.Column("course_class", sa.Integer),
    sa.Column("is_optional", sa.Boolean),
    sa.Column("section_id", sa.Integer)
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(course_table, [
        {"name": "Otomata Kuramı", "course_code": "EFC315", "course_semester": "Autumn", "course_class": 3, "section_id": 2, "is_optional": False},
        {"name": "Programlama Dilleri", "course_code": "SWE303", "course_semester": "Autumn", "course_class": 3, "section_id": 2, "is_optional": False},
        {"name": "Web Tasarımı ve Programlama", "course_code": "SWE307", "course_semester": "Autumn", "course_class": 3, "section_id": 2, "is_optional": False},
        {"name": "Bilgisayar Ağları", "course_code": "FET307", "course_semester": "Autumn", "course_class": 3, "section_id": 2, "is_optional": True},
        {"name": "Görsel Programlama", "course_code": "FET309", "course_semester": "Autumn", "course_class": 3, "section_id": 2, "is_optional": True},
        {"name": "Derin Öğrenme", "course_code": "FET312", "course_semester": "Autumn", "course_class": 3, "section_id": 2, "is_optional": True},
        {"name": "Python ile Programlama", "course_code": "FET210", "course_semester": "Autumn", "course_class": 3, "section_id": 2, "is_optional": True},
        {"name": "İşletim Sistemleri", "course_code": "EFC302", "course_semester": "Spring", "course_class": 3, "section_id": 2, "is_optional": False},
        {"name": "Mobil Uygulama Tasarımı ve Geliştirme", "course_code": "EFC304", "course_semester": "Spring", "course_class": 3, "section_id": 2, "is_optional": False},
        {"name": "Yazılım Projesi Geliştirme", "course_code": "EFC312", "course_semester": "Spring", "course_class": 3, "section_id": 2, "is_optional": False},
        {"name": "Bilişim Sistemleri ve Güvenliği", "course_code": "FET202", "course_semester": "Spring", "course_class": 3, "section_id": 2, "is_optional": True},
        {"name": "Kablosuz Ağlar", "course_code": "FET208", "course_semester": "Spring", "course_class": 3, "section_id": 2, "is_optional": True},
        {"name": "Uygulamalı Yapay Sinir Ağları", "course_code": "FET306", "course_semester": "Spring", "course_class": 3, "section_id": 2, "is_optional": True},
        {"name": "Makine Öğrenmesi", "course_code": "FET313", "course_semester": "Spring", "course_class": 3, "section_id": 2, "is_optional": True},
        {"name": "Oyun Tasarımı ve Programlama", "course_code": "FET310", "course_semester": "Spring", "course_class": 3, "section_id": 2, "is_optional": True},
        {"name": "Finansal Teknolojiler", "course_code": "FET336", "course_semester": "Spring", "course_class": 3, "section_id": 2, "is_optional": True},
        {"name": "Sunucu Taraflı Web Programlama", "course_code": "FET342", "course_semester": "Spring", "course_class": 3, "section_id": 2, "is_optional": True},
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
            DELETE FROM courses
            WHERE course_code IN (
                'EFC315',
            'SWE303','SWE307','FET307','FET309','FET312','FET210','EFC302','EFC304','FET202','FET208','FET306','FET313','FET310','FET336','FET342','EFC312'
            )
        """)
    # ### end Alembic commands ###
