"""add face encoding column

Revision ID: 43ef8851663a
Revises: eeffaaf56610
Create Date: 2026-02-22 16:03:48.882271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43ef8851663a'
down_revision: Union[str, Sequence[str], None] = 'eeffaaf56610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('face_encoding', sa.LargeBinary, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('users', 'face_encoding')
    # ### end Alembic commands ###
