"""add roles in role model

Revision ID: bf4a9dcb9880
Revises: 
Create Date: 2026-02-10 18:36:37.502303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf4a9dcb9880'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

roles_table = sa.table(
    "roles",
    sa.column("id", sa.Integer),
    sa.column("name", sa.String),
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(
        roles_table,
        [
            {"name": "ADMIN"},
            {"name": "STUDENT"},
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DELETE FROM roles WHERE name IN ('ADMIN', 'STUDENT')")
    
    # ### end Alembic commands ###
