"""add lessons to course v.3

Revision ID: d548e9c86492
Revises: fcfe23c88156
Create Date: 2026-02-14 17:36:31.856662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd548e9c86492'
down_revision: Union[str, Sequence[str], None] = 'fcfe23c88156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_courses_course_code",
        "courses",
        ["course_code"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_courses_course_code",
        "courses",
        type_="unique"
    )
    # ### end Alembic commands ###
