"""add lessons to course v.4

Revision ID: e620fab49bdb
Revises: d548e9c86492
Create Date: 2026-02-14 17:55:48.893954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e620fab49bdb'
down_revision: Union[str, Sequence[str], None] = 'd548e9c86492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

course_table = sa.Table(
    "courses",
    sa.MetaData(),
    sa.Column("id", sa.Integer),
    sa.Column("name", sa.String),
    sa.Column("course_code", sa.String),
    sa.Column("course_semester", sa.String),
    sa.Column("course_class", sa.Integer),
    sa.Column("is_optional", sa.Boolean),
    sa.Column("section_id", sa.Integer)
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(
        course_table,
        [
            {"name": "Matematik I", "course_code": "FEC101", "course_semester": "Autumn", "course_class": 1, "section_id": 2, "is_optional": True},
            {"name": "Fizik I", "course_code": "FEC103", "course_semester": "Autumn", "course_class": 1, "section_id": 2, "is_optional": True},
            {"name": "Türk Dili I ", "course_code": "URC113", "course_semester": "Autumn", "course_class": 1, "section_id": 2, "is_optional": True},
            {"name": "Ingilizce", "course_code": "URC101", "course_semester": "Autumn", "course_class": 1, "section_id": 2, "is_optional": True},
            {"name": "Atatürk İlkeleri ve İnkılap Tarihi I", "course_code": "URC111", "course_semester": "Autumn", "course_class": 1, "section_id": 2, "is_optional": True},
            {"name": "Yazılım Mühendisliğine Giriş", "course_code": "SWE101", "course_semester": "Autumn", "course_class": 1, "section_id": 2, "is_optional": True},
            {"name": "Programlama I", "course_code": "EFC113", "course_semester": "Autumn", "course_class": 1, "section_id": 2, "is_optional": True},

            {"name": "Programlama II", "course_code": "EFC102", "course_semester": "Spring", "course_class": 1, "section_id": 2, "is_optional": True},
            {"name": "Matematik II", "course_code": "FEC102", "course_semester": "Spring", "course_class": 1, "section_id": 2, "is_optional": True},
            {"name": "Ayrık Matematik", "course_code": "FEC108", "course_semester": "Spring", "course_class": 1, "section_id": 2, "is_optional": True},
            {"name": "Yazılım Mühendisliğinin Temelleri", "course_code": "SWE102", "course_semester": "Spring", "course_class": 1, "section_id": 2, "is_optional": True},
            {"name": "Kariyer Planlama", "course_code": "URC110", "course_semester": "Spring", "course_class": 1, "section_id": 2, "is_optional": True},
            {"name": "Atatürk İlkeleri ve İnkılap Tarihi II", "course_code": "URC112", "course_semester": "Spring", "course_class": 1, "section_id": 2, "is_optional": True},
            {"name": "Türk Dili II", "course_code": "URC114", "course_semester": "Spring", "course_class": 1, "section_id": 2, "is_optional": True},

            {"name": "Mesleki İngilizce", "course_code": "CME201", "course_semester": "Autumn", "course_class": 2, "section_id": 2, "is_optional": True},
            {"name": "Veri Yapıları ve Algoritmalar", "course_code": "EFC201", "course_semester": "Autumn", "course_class": 2, "section_id": 2, "is_optional": True},
            {"name": "Nesne Tabanlı Programlama Temelleri", "course_code": "EFC203", "course_semester": "Autumn", "course_class": 2, "section_id": 2, "is_optional": True},
            {"name": "Olasılık ve İstatistik", "course_code": "FEC201", "course_semester": "Autumn", "course_class": 2, "section_id": 2, "is_optional": True},
            {"name": "Lineer Cebir", "course_code": "FEC207", "course_semester": "Autumn", "course_class": 2, "section_id": 2, "is_optional": True},
            {"name": "Bilgisayar Organizasyonu", "course_code": "SWE201", "course_semester": "Autumn", "course_class": 2, "section_id": 2, "is_optional": True},

            {"name": "Nümerik Analiz", "course_code": "EFC202", "course_semester": "Spring", "course_class": 2, "section_id": 2, "is_optional": True},
            {"name": "Veritabanı Yönetim Sistemleri", "course_code": "EFC204", "course_semester": "Spring", "course_class": 2, "section_id": 2, "is_optional": True},
            {"name": "İş Sağlığı ve Güvenliği", "course_code": "FEC204", "course_semester": "Spring", "course_class": 2, "section_id": 2, "is_optional": True},
            {"name": "Diferansiyel Denklemler", "course_code": "FEC206", "course_semester": "Spring", "course_class": 2, "section_id": 2, "is_optional": True},
            {"name": "Yazılım Mimarisi", "course_code": "SWE202", "course_semester": "Spring", "course_class": 2, "section_id": 2, "is_optional": True},
            {"name": "Genel Kimya", "course_code": "FET212", "course_semester": "Spring", "course_class": 2, "section_id": 2, "is_optional": False},
            {"name": "Kuantum Fiziği", "course_code": "FET214", "course_semester": "Spring", "course_class": 2, "section_id": 2, "is_optional": False},
            {"name": "Modern Biyolojinin Temelleri", "course_code": "FET216", "course_semester": "Spring", "course_class": 2, "section_id": 2, "is_optional": False},
            {"name": "Fizik II", "course_code": "FET218", "course_semester": "Spring", "course_class": 2, "section_id": 2, "is_optional": False},
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    def downgrade():
        op.execute("""
            DELETE FROM courses
            WHERE course_code IN (
                'FEC101','FEC103','URC113','URC101','URC111','SWE101','EFC113',
                'EFC102','FEC102','FEC108','SWE102','URC110','URC112','URC114',
                'CME201','EFC201','EFC203','FEC201','FEC207','SWE201',
                'EFC202','EFC204','FEC204','FEC206','SWE202','FET212','FET214','FET216','FET218'
            )
        """)
    # ### end Alembic commands ###
