"""add role teacher

Revision ID: eeffaaf56610
Revises: 06d403e09fdb
Create Date: 2026-02-19 09:31:52.159660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeffaaf56610'
down_revision: Union[str, Sequence[str], None] = '06d403e09fdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

roles_table = sa.table(
    "roles",
    sa.column("id", sa.Integer),
    sa.column("name", sa.String),
)

def upgrade() -> None:
    """Upgrade schema."""
    op.bulk_insert(
        roles_table,
        [
            {"name": "TEACHER"}
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM roles WHERE name IN ('TEACHER')")
    # ### end Alembic commands ###
