"""add lessons to course

Revision ID: f9b7e6e05d58
Revises: bf4a9dcb9880
Create Date: 2026-02-14 16:19:38.850034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9b7e6e05d58'
down_revision: Union[str, Sequence[str], None] = 'bf4a9dcb9880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None




def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses',sa.Column('course_code', sa.String, nullable=False))
    op.add_column('courses', sa.Column('course_semester', sa.String, nullable=False))
    op.add_column('courses', sa.Column('course_class', sa.Integer, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'course_code')
    op.drop_column('courses', 'course_semester')
    op.drop_column('courses', 'course_class')
    # ### end Alembic commands ###
