"""add lessons to course v.2

Revision ID: fcfe23c88156
Revises: f9b7e6e05d58
Create Date: 2026-02-14 16:59:39.697373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'fcfe23c88156'
down_revision: Union[str, Sequence[str], None] = 'f9b7e6e05d58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("courses", sa.Column("is_optional", sa.Boolean, default=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("courses", "is_optional")
    # ### end Alembic commands ###
